[package]
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
edition = "2021"
name = "kabina-db"
version = "0.0.1"

[dependencies]
salsa = { git = "https://github.com/salsa-rs/salsa", package = "salsa-2022" }
dashmap = "5.4.0"
globset = "0.4.10"
indexmap = "1.9.3"
walkdir = "2.3.3"
by_address = "1.1.0"
tracing = "0.1.37"
serde = "*"
serde_json = "1.0.95"
downcast-rs = "1.2.0"
anyhow = "1.0.70"
thiserror = "1.0.40"
parking_lot = "0.12.1"
