[workspace]
members = [
  "packages/kabina-cli",
  "packages/kabina-rt",
  "packages/kabina-ui",
  "packages/kabina-db"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
# lto = true

[profile.bench]
# lto = true
debug = true