[package]
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
edition = "2021"
name = "kabina-cli"
version = "0.0.4"

[dependencies]
clap= { version = "4.1.4", features = ["derive"] }
kabina-rt={ path = "../kabina-rt" }
kabina-db={ path = "../kabina-db" }
tokio={ version = "1.25.0", features = ["full"] }
tracing-subscriber= "0.3.16"
parking_lot="*"