[package]
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
edition = "2021"
name = "kabina-cli"
version = "0.0.4"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
kabina-rt = { path = "../kabina-rt" }
kabina-db = { path = "../kabina-db" }
kabina-rpc = { path = "../kabina-rpc" }
tokio = { version = "1.27.0", features = ["full"] }
tracing-subscriber = "0.3.16"
parking_lot = "0.12.1"
paste = "1.0.12"
which = "*"
tracing = "*"
daemonize = "0.5.0"
futures = "*"
tarpc = { version = "*", features=["full"] }
anyhow="*"
const-random="*"
url="*"