[package]
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
edition = "2021"
name = "kabina-rt"
version = "0.0.4"

[dependencies]
deno_core= "0.171.0"
deno_ast={ version = "0.24.0", features = ["transpiling"] }
anyhow= "1.0.69"
futures= "0.3.26"
serde= "1.0.152"
tracing= "0.1.37"
tokio={ version = "1.25.0", features = ["full"] }
kabina-db={path="../kabina-db"}
